
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '0.17'
          - '0.17/alpine'
          - '0.15'
          - '0.15/alpine'
      fail-fast: false